### ISSUE TITLE
I am getting the following error when running `--help`

### ISSUE THREAD

**Issue by LZiHaN** [vajahath/open-swagger-ui#21]
internal/util.js:257
    throw new ERR_INVALID_ARG_TYPE('original', 'Function', original);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type Function. Received type undefined
    at promisify (internal/util.js:257:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/open-swagger-ui/node_modules/compress-brotli/src/index.js:9:18)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/open-swagger-ui/node_modules/keyv/src/index.js:5:24)

**Comment by qb-vajahath** [comment]
Could you please provide a few more details like the OS and the command you tried?

**Comment by vajahath** [comment]
Could you please provide a few more details like the OS you are using and the command you tried?

**Comment by LZiHaN** [comment]
macOS 10.13.6.  #

➜  ~ open-swagger-ui --help
internal/util.js:257
    throw new ERR_INVALID_ARG_TYPE('original', 'Function', original);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type Function. Received type undefined
    at promisify (internal/util.js:257:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/open-swagger-ui/node_modules/compress-brotli/src/index.js:9:18)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/open-swagger-ui/node_modules/keyv/src/index.js:5:24)

**Comment by vajahath** [comment]
```
$ open-swagger-ui --version
1.2.0
$ open-swagger-ui --help
Usage: open-swagger-ui [options] <swagger-file>

An easy CLI tool to open swagger.json or .yaml files in Swagger UI.

Options:
  -V, --version      output the version number
  -O, --open         Open stuff in browser
  -P, --port <port>  Preferred port. If not available, a random port is selected
  -h, --help         output usage information
```
I was not able to reproduce this on Ubuntu. I don't have a mac. Can you debug this?
